[package]
name = "caseta"
version = "0.1.0"
authors = ["Shane Snover <ssnover95@gmail.com>"]
edition = "2018"

[dependencies]
openssl = "0.10"
rand = "0.8"
rsa = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"